// Frontend/find-group-react/src/routes/group/UserGroups.tsx
import React, {useEffect, useState, MouseEvent} from 'react';
import useAxiosPrivate from "../../hooks/useAxiosPrivate";
import {GroupService} from "../../services/GroupService";
import {IGroup} from "../../domain/IGroup";
import GroupCard from "../../components/group/GroupCard";
import {ButtonGroup} from "react-bootstrap";
import {Link, useNavigate} from "react-router-dom";
import GroupsNav from "../../components/group/GroupsNav";

const UserGroups = () => {
    const axiosPrivate = useAxiosPrivate();
    const groupService = new GroupService(axiosPrivate);
    const [groupsToShow, setGroupsToShow] = useState([] as IGroup[]);

    useEffect(() => {
        groupService.getJoinedGroups().then(g => {
            setGroupsToShow(g);
        })
    }, []);

    return (
        <div className="container">

            <GroupsNav/>

            <div className="card-deck mt-4">
                <div className="row row-cols-1 row-cols-sm-1 row-cols-md-2 row-cols-lg-3 row-cols-xl-4">
                    {groupsToShow.map(group => (
                        <GroupCard key={group.id} value={group} link={'../group/' + group.id}/>
                    ))}
                </div>
            </div>
        </div>
    );
};

export default UserGroups;

// Frontend/find-group-vue/src/views/group/UserGroups.vue
<script lang="ts">
import { defineComponent } from "vue";
import GroupCards from "../../components/GroupCards.vue";
import GroupNav from "../../components/GroupNav.vue";
import { GroupService } from "../../services/GroupService";
import { useUserGroupStore } from "../../stores/userGroups";

export default defineComponent({
  components: { GroupCards, GroupNav },
  name: "UserGroups",
  setup() {
    const groupStore = useUserGroupStore();
    const groupService = new GroupService();
    const groupResponse = groupService.getJoinedGroups().then((g) => {
      groupStore.set(g);
    });
    return {
      groupStore,
    };
  },
});
</script>

<template>
  <div class="container">
    <group-nav></group-nav>
    <div class="card-deck mt-4">
      <div
        className="row row-cols-1 row-cols-sm-1 row-cols-md-2 row-cols-lg-3 row-cols-xl-4"
      >
        <group-cards></group-cards>
      </div>
    </div>
  </div>
</template>
